import random

# LA CLASE DE LOS DICCIONARIOS ES DICT
d = {1: "Paco", 77: 34, 12: True}
# SI SE IMPRIME EN PANTALLA EL DICCIONARIO AL COMPLETO SE IMPRIME TANTO LA CLAVE COMO EL VALOR
print(d)

numero_random = random.randint(0, 100)
numero_aleatorio = random.randint(0, 100)
# COMO AÑADIR VALORES A LOS DICCIONARIOS
# OPCION 1
d[numero_random] = numero_aleatorio
# OPCION 2
diccionario_nuevo = {6: "Andoni", 8: "Andamio", 0: 55}
d.update(diccionario_nuevo)

# COMO ACCEDER A LOS VALORES DE UN DICCIONARIO
# OPCION 1 - MEDIANTE []
valor_diccionario = d[12] # EN CASO DE QUE NO EXISTA EL VALOR DEL CODIGO EN EL DICCIONARIO DARA ERROR

# OPCION 2 - ACCESO MEDIANTE EL GET
nombre = d.get(1) # MEDIANTE ESTE METODO EN CASO DE NO EXISTIR EL VALOR DEL CODIGO EN EL DICCIONARIO NOMBRE = NONE
valor = diccionario_nuevo.get(20, "Valor por defecto") # CON EL GET TENEMOS POR UN LADO EL CODIGO DEL DICCIONARIO Y EN CASO DE NO EXISTIR ESE CODIGO EN EL DICCIONARIO SE LE CREARA UNO NUEVO Y SE LE ASIGNARA EL VALOR PUESTO DESPUES DE LA COMA

# COMO ELIMINAR VALORES DE UN DICCIONARIO
# MEDIANTE LA PALABRA DEL
del d[numero_random] # ENTRE LOS [] SE COLOCA EL CODIGO DEL DICCIONARIO

# MEDIANTE EL METODO POP
item_eliminado = d.pop(numero_random, 0) # EL PRIMER VALOR SERIA EL CODIGO DEL DICCIONARIO Y EL SEGUNDO VALOR SERIA EL VALOR QUE OBTENDRIA LA VARIABLE EN CASO DE NO ENCONTRAR EL PRIMER VALOR EN EL DICCIONARIO

# MEDIANTE EL METODO POPITEM
pop_item = diccionario_nuevo.popitem() # NOS DEVUELVE EL ULTIMO PAR CLAVE-VALOR INSERTADO DE UN DICCIONARIO COMO UNA TUPLA

# DIFERENTES METODOS DE LA CLASE DICT
# METODO CLEAR
diccionario_nuevo.clear() # ESTO VACIA EL DICCIONARIO

# METODO COPY
copia = d.copy() # ESTO HACE UNA COPIA COMPLETA DEL DICCIONARIO

# METODO KEYS
claves = d.keys() # ESTO NOS DEVUELVE TODOS LOS CODIGOS DEL DICCIONARIO

# METODO VALUES
valores_diccionario = d.values() # ESTO NOS DEVUELVE TODOS LOS VALORES DE NUESTRO DICCIONARIO SIN SU CORRESPONDIENTE CODIGO

# METODO ITEMS
items = d.items() # ESTO NOS DEVUELVE UNA LISTA DE TUPLAS CON TODOS LOS CODIGOS Y VALORES DENTRO DEL DICCIONARIO
